# Generated by Django 4.2.9 on 2024-04-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="/media/authentification/images/profile_pictures/bear.png",
                upload_to="authentification/images/profile_pictures/",
            ),
        ),
    ]
