# Generated by Django 4.2.9 on 2024-04-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bracket",
            name="match_list",
            field=models.ManyToManyField(to="game.match"),
        ),
    ]
