# Generated by Django 4.2.9 on 2024-04-25 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tournament", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="hittingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hittingZone", models.CharField(default="0,0", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="scoreTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scoreTime", models.CharField(default="0,0", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                ("first_player_point", models.IntegerField(default=0)),
                (
                    "first_pseudo",
                    models.CharField(
                        blank=True, default="default", max_length=100, null=True
                    ),
                ),
                ("second_player_point", models.IntegerField(default=0)),
                (
                    "second_pseudo",
                    models.CharField(
                        blank=True, default="default", max_length=100, null=True
                    ),
                ),
                (
                    "victory_pseudo",
                    models.CharField(
                        blank=True, default="default", max_length=100, null=True
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("left_hits", models.IntegerField(default=0)),
                ("right_hits", models.IntegerField(default=0)),
                ("total_hits", models.IntegerField(default=0)),
                ("game_length", models.IntegerField(default=0)),
                (
                    "first_user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_player",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("hitting_zone", models.ManyToManyField(to="game.hittingzone")),
                (
                    "score_time_p1",
                    models.ManyToManyField(
                        related_name="score_time_p1", to="game.scoretime"
                    ),
                ),
                (
                    "score_time_p2",
                    models.ManyToManyField(
                        related_name="score_time_p2", to="game.scoretime"
                    ),
                ),
                (
                    "second_user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_player",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.tournament",
                    ),
                ),
                (
                    "victory_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
